name       : python-zope.testing
version    : 4.9
release    : 1
source     :
    - https://github.com/zopefoundation/zope.testing/archive/refs/tags/4.9.tar.gz : 6f8c8a6f39dae86f95cdff33e36e37909db69ac6b4ea7eb09ad83d957545cb58
license    : ZPL-2.1
component  : programming.python
summary    : This package provides a number of testing frameworks.
description: |
    This package provides a number of testing frameworks.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
